#!/usr/bin/python3

__author__="distcoll"
__license__="MIT License"
__api__="https://github.com/4chan/4chan-API"

import requests
import os
import sys
def main():
	
###change this to use argparse!

	#setting up board and thread number, regardless of
	#command line order and also allowing no command line
	#inputs
	try:
		inp1=sys.argv[1]
		inp2=sys.argv[2]
		inp=True
	except IndexError:
		inp=False
		#help dialog if user enters -h or --help from
		#the command line
		if sys.argv[1].strip()=="-h" or sys.argv[1].strip()=="--help":
			print("\n\ngive the program the board abbreviation and thread number either as command line arguments or when prompted\n")
			sys.exit(1)
	if inp:
		try:
			number=int(inp1)
			board=inp2.strip()
		except ValueError:
			number=int(inp2)
			board=inp1.strip()
		number=str(number)

	else:
		board=input("board?:\t").strip()
		number=input("thread number?:\t").strip()


	#retrieving the json of the thread using 4chan API
	try:
		data=requests.get("http://a.4cdn.org/"+board+"/thread/"+number+".json")
	except:
		print("tbd")
		sys.exit(1)
	#need a new error handler here
#	except urllib.error.HTTPError:
#		print("thread not found, exiting...")
#		sys.exit(1)

	#notifying user of what's being downloaded
	print("Downloading http://boards.4chan.org/"+board+"/thread/"+number+" -- "+data.json()["posts"][0]["semantic_url"]+'\n')


##move this part up to the top in this and continuous.py so that if there is an error, it happens sooner

	#creating a folder to store downloaded files
	#if it already exists, move to it
	fol=data.json()["posts"][0]["semantic_url"]
	if os.path.exists(fol):
		os.chdir(fol)
	else:
		os.mkdir(fol)
		os.chdir(fol)

	#download all the files using 4chan API
	#if a file exists, skip it
	for i in data.json()["posts"]:
		if "fsize" in i:
			if os.path.exists(i["filename"]+i["ext"]):
				continue
			with open(i["filename"]+i["ext"],"wb") as file:
				pic=requests.get("https://i.4cdn.org/"+board+'/'+str(i["tim"])+i["ext"])
				for part in pic.iter_content(4096):
					file.write(part)

if __name__=="__main__":
	try:
		main()
	except KeyboardInterrupt:
		print("User exit with keyboard interrupt, exiting...")
		sys.exit(1)
	except:
		raise
